# Generated by Django 4.1.5 on 2023-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('serial_number', models.CharField(max_length=15)),
                ('computer_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('year_purchased', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('serial_number', models.CharField(max_length=15)),
                ('computer_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('year_purchased', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('year_purchased', models.DateField(blank=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('year_purchased', models.DateField()),
                ('ram', models.CharField(max_length=8)),
                ('storage_capacity', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=25)),
                ('application', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
