# Generated by Django 4.1.6 on 2023-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='server',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='desktop',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desktop',
            name='serialnumber',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='serialnumber',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='serialnumber',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='serialnumber',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='year_purchased',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='year_purchased',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='year_purchased',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='year_purchased',
            field=models.CharField(max_length=4),
        ),
    ]
