# Generated by Django 4.1.6 on 2023-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_desktop_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='year_purchased',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
